PubmedID,Title,Publication Date,Non-academic Authors,Company Affiliations,Corresponding Author Email
40054036,Clinical benefits of CT-guided microwave ablation combined with percutaneous vertebroplasty for spinal metastases: Local tumor control and a multivariate analysis of bone cement leakage.,,N/A,N/A,N/A
40054035,Quantitative prediction of drug disposition for uridine diphosphate-glucuronosyltransferase substrates using humanized mice.,,"Taiji Miyake, Yuito Fujita, Manabu Hirabayashi, Natsuko Komiyama, Keiichi Morita, Tatsuhiko Tachibana, Kimio Terao","Pharmaceutical Science Department, Translational Research Division, Chugai Pharmaceutical Co., Ltd., Yokohama-shi, Japan. Electronic address: miyake.taiji61@chugai-pharm.co.jp., Pharmaceutical Science Department, Translational Research Division, Chugai Pharmaceutical Co., Ltd., Yokohama-shi, Japan., Experimental Technology Department, Chugai Research Institute for Medical Science Inc., Yokohama-shi, Japan., Experimental Technology Department, Chugai Research Institute for Medical Science Inc., Yokohama-shi, Japan., Pharmaceutical Science Department, Translational Research Division, Chugai Pharmaceutical Co., Ltd., Yokohama-shi, Japan., Pharmaceutical Science Department, Translational Research Division, Chugai Pharmaceutical Co., Ltd., Yokohama-shi, Japan. Electronic address: tachibanatth@chugai-pharm.co.jp., Pharmaceutical Science Department, Translational Research Division, Chugai Pharmaceutical Co., Ltd., Yokohama-shi, Japan.",N/A
40054034,"Pluripotent stem cell-derived mesenchymal stem cells for therapeutic applications, developmental study, and cancer research.",,N/A,N/A,N/A
40054032,Unusual blister on the arm.,,N/A,N/A,N/A
40054031,Paradoxical erosive oral lichen planus possibly induced by abatacept.,,N/A,N/A,N/A
40054030,Immunotherapy-responsive parkinsonism and anosmia in anti-NMDA receptor encephalitis with seropositive NMOSD: A case report.,,N/A,N/A,N/A
40054028,Association between body composition parameters and treatment-related toxicities in patients with metastatic breast cancer receiving cyclin-dependent kinase 4 and 6 inhibitors.,,N/A,N/A,N/A
40054027,Core elements and principles of nutrition models of care for people with cancer: A scoping review.,,N/A,N/A,N/A
40054026,Dataset-free weight-initialization on restricted Boltzmann machine.,,Ryosuke Maeno,"Techno Provide Inc., Honcho 1-1-8, Aoba-ku, Sendai, 980-0014, Miyagi, Japan.",N/A
40054025,Continual learning of conjugated visual representations through higher-order motion flows.,,N/A,N/A,N/A
